### ISSUE TITLE
Document how initoverlayfs works under the hood

### ISSUE THREAD

**Issue by jlebon** [containers/initoverlayfs#26]
The project name includes "overlayfs" but the README doesn't mention where overlayfs is actually used. Maybe a small section in the README that describes how each component is built and then goes through the boot flow step-by-step from the initramfs to the initoverlayfs?

**Comment by ericcurtin** [comment]
I'm in the middle of updating the readme, thanks for the feedback will add.

**Comment by ericcurtin** [comment]
Hence overlayfs is in the name and not erofs... And it's the overlay that creates the transient behaviour...

**Comment by jlebon** [comment]
Thanks! The new README looks good.
