### ISSUE TITLE
Push a new release (0.98) to Fedora Rawhide

### ISSUE THREAD

**Issue by ericcurtin** [containers/initoverlayfs#35]

**Comment by ericcurtin** [comment]
@Smooge

**Comment by ericcurtin** [comment]
I think we completed this push to rawhide @smooge ? The automotive copr would be a good idea also, for the other platforms...

**Comment by ericcurtin** [comment]
Feel free to close anyway if the above is true of course

**Comment by smooge** [comment]
This has been pushed to rawhide, el9 and f39
