### ISSUE TITLE
pipeline for testing changes

### ISSUE THREAD

**Issue by dougsland** [containers/initoverlayfs#5]
This is not trivial software for testing as it would require a full boot process but let's create a minimal CI/CD pipeline to run before merges.

**Comment by dougsland** [comment]
Some ideas:
 
 - tools to validate the code
 - sync2jira (generate a jira as soon the project has a new issue)
 - if possible generate initramfs images before and after the change and compare sizes

@ericcurtin feel free to add more tests.

**Comment by ericcurtin** [comment]
These are good ideas.

We should also do a podman container with krun runtime that tests this end to end. The reason you want a hypervisor is this messes around with low-level details within an OS and you probably want that isolated in a VM as well as a container, otherwise you could mount and unmount partitions in your base os.

**Comment by Yarboa** [comment]
@dougsland 
I would suggest packit infrastructure, with tmt basic scenario over c9s.
Should it be on different issues?

**Comment by dougsland** [comment]
> @dougsland I would suggest packit infrastructure, with tmt basic scenario over c9s. Should it be on different issues?
> 
> One more thing here, packit rpm build, Shall I open a ticket for that also?

Hey @Yarboa, glad to see you around here too. Lets open an exclusive ticket for tmt infrastructure as it's used downstream/upstream in others auto projects.

**Comment by Yarboa** [comment]
Closing this
#28 already test the minimum scenario and reboot

**Comment by Yarboa** [comment]
Closing this
https://github.com/containers/initoverlayfs/pull/28 
already test the minimum scenario and reboot
