### ISSUE TITLE
packit infrastructure, with tmt basic scenario over c9s

### ISSUE THREAD

**Issue by dougsland** [containers/initoverlayfs#9]
As @yarboa mentioned, we need additional infrastructure for tests to be aligned with others auto components:

- packet infrastructure with tmt basic scenario over c9s
- packit rpm build

**Comment by Yarboa** [comment]
@dougsland shall we automate this one? 
https://github.com/containers/initoverlayfs#initoverlayfs

**Comment by dougsland** [comment]
> @dougsland shall we automate this one? https://github.com/containers/initoverlayfs#initoverlayfs

yes, please, would be super nice to have!

**Comment by ericcurtin** [comment]
I added @mwperina as a collaborator with write access if it helps

**Comment by Yarboa** [comment]
c9s has single image deployment in destingfarm
#29 #33 , I have to debug disk partition on TF aws image

**Comment by ericcurtin** [comment]
We have some infrastructure more is always helpful! But gonna close this for now
